name: workbench_workflow

# Controls when the workflow will run
on:
  # default workflow runs for all branches and tags
  push:
    branches: '**' 
    tags: '**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a one job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java and Maven
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          # https://github.com/actions/setup-java#supported-distributions
          distribution: 'adopt'
        
        # --batch-modes and --update-snapshots
      - name: Build OS binaries and p2 artifacts
        id: maven-verify
        run: mvn -B -U verify

      - name: Set version [TAG]
        run: ./setversion.sh ${{ github.ref_name }} && ./io.opencaesar.rosetta.product/setversion.sh 
        if: ${{ github.ref_type == 'tag' }} # Run job on tag only

      - name: Upload Artifacts and Create Github Release [TAG]
        # ${{ github.ref_name }} is most recent tag name.  For workflows triggered by push, this is the branch or tag ref that was pushed.
        # https://docs.github.com/en/actions/learn-github-actions/contexts
        run: |
          set -x
          artifacts=()
          for a in ${{ env.ZIP_PRODUCTS_PATH }}; do
            artifacts+=("-a" "$artifact")
          done
          tag_name=${{ github.ref_name }}
          hub release create "${artifacts[@]}" -m "$tag_name" "$tag_name"
        if: ${{ github.ref_type == 'tag' }} # Run job on tag only
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}

      # TODO: Create signing step for MacOS binaries current workaround
      # xattr -cr /path/to/mac_application.app

      - name: Deploy p2 artifacts [TAG]
        run: mvn deploy -Prelease-composite -Dgithub-update-repo=https://x-access-token:${{ secrets.ACTIONS_TOKEN }}@github.com/pogi7/oml-rosetta-p2
        if: ${{ github.ref_type == 'tag' }} # Run job on tag only
